knowledge_base_name: 'complaints-assistant'
knowledge_base_description: 'bedrock-allow'
kb_files_path: 'kb_files'
table_name: 'complaints-assistant-master'
pk_item: 'complaint_id'
sk_item: 'client_id'
person_table_name: 'person-master'
